version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ../../my-api-backend   # ← 修正ポイント
    container_name: api-server
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: myapp
      DB_PORT: 5432
    volumes:
      - ../../my-api-backend:/app
    working_dir: /app
    command: sh -c "npx sequelize-cli db:migrate && npm run dev"

  web:
    build:
      context: ../                    # ← deploy/ の1つ上 = my-ui-frontend
    container_name: frontend-app
    ports:
      - '5173:5173'
    volumes:
      - ../:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - api

volumes:
  db-data:
